# Generated by Django 3.2.3 on 2021-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='choice',
            field=models.CharField(choices=[('national', 'National'), ('international', 'International')], max_length=13),
        ),
    ]
